### ISSUE TITLE
[BUG] Error when trying to use /ah sell

### ISSUE THREAD

**Issue by JerichoTorrent** [Finally-A-Decent/Fadah#20]
**Describe the bug**
I tried to use /ah sell to sell an item and got this error:
```
java.lang.RuntimeException: No value at path currency.icon
        at Fadah-Bukkit-2.7.1.jar/info.preva1l.fadah.utils.config.LanguageConfig.getAsMaterial(LanguageConfig.java:52) ~[Fadah-Bukkit-2.7.1.jar:?]
        at Fadah-Bukkit-2.7.1.jar/info.preva1l.fadah.guis.NewListingMenu.setCurrencyButton(NewListingMenu.java:172) ~[Fadah-Bukkit-2.7.1.jar:?]
        at Fadah-Bukkit-2.7.1.jar/info.preva1l.fadah.guis.NewListingMenu.<init>(NewListingMenu.java:80) ~[Fadah-Bukkit-2.7.1.jar:?]
        at Fadah-Bukkit-2.7.1.jar/info.preva1l.fadah.commands.subcommands.SellSubCommand.execute(SellSubCommand.java:77) ~[Fadah-Bukkit-2.7.1.jar:?]
        at Fadah-Bukkit-2.7.1.jar/info.preva1l.fadah.utils.commands.SubCommand.lambda$executor$3(SubCommand.java:56) ~[Fadah-Bukkit-2.7.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**To Reproduce**
1. Use /ah sell on any item

**Expected behavior**
The item is listed for auction.

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Server Type: Pufferfish (latest build) behind Velocity
 - Server Version: 1.21.1
 - Plugin Version: 2.7.1

**Additional context**
This only started happening on the latest build.

**Comment by ProdPreva1l** [comment]
Regenerate the `menus/new-listing.yml` file

**Comment by JerichoTorrent** [comment]
Will try it
