### ISSUE TITLE
[BUG] I get an error when I use /ah sell

### ISSUE THREAD

**Issue by Onism02** [Finally-A-Decent/Fadah#24]
**Describe the bug**
`[00:00:02 WARN]: [Fadah] Task #1892 for Fadah v2.7.4 generated an exception
java.lang.NullPointerException: Cannot invoke "info.preva1l.fadah.currency.Currency.getName()" because "this.currency" is null
        at info.preva1l.fadah.guis.NewListingMenu.setCurrencyButton(NewListingMenu.java:168) ~[?:?]
        at info.preva1l.fadah.guis.NewListingMenu.<init>(NewListingMenu.java:80) ~[?:?]
        at info.preva1l.fadah.commands.subcommands.SellSubCommand.execute(SellSubCommand.java:64) ~[?:?]
        at info.preva1l.fadah.utils.commands.SubCommand.lambda$executor$3(SubCommand.java:56) ~[?:?]
        at info.preva1l.fadah.utils.TaskManager$Sync.lambda$run$0(TaskManager.java:26) ~[?:?]
        at info.preva1l.fadah.libs.multilib.regionized.bukkit.BukkitRegionizedTaskWrapper.run(BukkitRegionizedTaskWrapper.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.12-universal.jar%23203!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.3.12-universal.jar%23203!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1137) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]`
**To Reproduce**
1. Use /ah sell

**Expected behavior**
The item should be listed

**Screenshots**
None

**Environment (please complete the following information):**
 - OS Windows 11
 - Server Type Mohist - 1.20.1-915, Java(61.0) 17.0.8
 - Server Version 1.20.1
 - Plugin Version 2.7.4

**Additional context**
none

**Comment by ProdPreva1l** [comment]
The default currency in config.yml is not loaded
